### ISSUE TITLE
Joint Centers not properly calculated for walking datasets

### ISSUE THREAD

**Issue by ajlewis02** [nag92/AIM_Vicon#15]
(This is the one I told you about a few weeks ago, just thought I'd actually write it down.)

Whether calculated using the calibration data and applied to the walking data, or calculated directly with the walking data, the joint center positions are highly inaccurate.

**Comment by ajlewis02** [comment]
Very likely caused in part by #16, but this happens to the left leg joints as well so it can't be the only problem.

**Comment by nag92** [comment]
yea, im not surprised.

**Comment by ajlewis02** [comment]
Upon further investigation, it seems that this isn't actually a bug on our end.

When calibration data joints are applied to walking datasets, most of the joints _are_ totally accurate. Inaccuracy seems to be caused when certain rigid bodies appear to rotate in place. This is almost certainly an issue with the motion capture system, and not any of our software.

In particular, in the subject 3 walk 0 dataset, the right femur and left tibia both appear to rotate several times each over the span of the data. This causes the right knee and left ankle joints to appear out of place. Despite this, the rest of the joints (both hips, left knee, and right ankle) are all positioned correctly.

**Comment by nag92** [comment]
interesting. ill take a look, This "might" have to do with the marker assainment. If the system looses track of a marker(s) it is possible that it will switch two markers. which would cause this problem.
